networks:
  development:
  test:
volumes:
  db_data:
  shared_data:
services:
  arc_redis:
    image: redis:7.2-alpine
    command: ["redis-server"]
    networks:
      - development
      - test
    volumes:
      - shared_data:/var/shared/redis
  db:
    image: postgres:16-alpine
    container_name: arc_db
    volumes:
      - db_data:/var/lib/postgresql/data
      - shared_data:/var/shared
    networks:
      - development
      - test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5099:5432
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: arc_app
    volumes:
      - .:/rails
      - shared_data:/var/shared
    networks:
      - development
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    env_file: .env.development
    entrypoint: ["./bin/docker-entrypoint"]
    command: ["./bin/rails", "server", "-p", "3000", "-b", "0.0.0.0"]
    environment:
      RAILS_ENV: development
    depends_on:
      - db
      - arc_redis
